### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by joseluistorres** [Iowa-Elixir/reunions#1]
I'm not sure if this should be more than one card or not. In ruby, it would be only one card (thank you devise). Not sure what the effort is like in Elixir/Phoenix.

I'll try https://github.com/smpallen99/coherence

**Comment by ctreptow** [comment]
Coherence looks good on the surface.  I think one card it just fine.

**Comment by cartothemax** [comment]
I think Coherence will be good for our purposes!  It's extensible and well documented too.

**Comment by joseluistorres** [comment]
Looks good so far, I'm following the steps there.

**Comment by codebycliff** [comment]
This has been merged.
