### ISSUE TITLE
Reunion model

### ISSUE THREAD

**Issue by codebycliff** [Iowa-Elixir/reunions#2]
* Location (Maybe city + state)
* Title
* Description

This was modeled after meetup.com. Meetups also have topics (essentially tags). Not sure if want that in the first release or not.

**Comment by codebycliff** [comment]
I'm going to knock this guy out. I just plan to create the model and migration to start with. I could also scaffold and we could delete what we don't need. What are your guys opinion on this? @ctreptow @joseluistorres @cartothemax.

**Comment by joseluistorres** [comment]
Go ahead @codebycliff  I'll wait for that one to finish #1 I'll have a PR during the day

**Comment by ctreptow** [comment]
Start simple.  Go for it!

**Comment by cartothemax** [comment]
I agree with @ctreptow go with simpler for now.  It could be worthwhile to break location info into multiple fields for the future (Address1, address2, city, state, etc.)

For now I say keep it to a simple Location field and we can expand it later on.

**Comment by codebycliff** [comment]
This has been merged.
